# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Green.create([
  { name: "artichoke", description: "", sow_period: 3..4, grow_period: 5..8, harvest_period: 8..9 },
  { name: "celtuce", description: "Sometimes called asparagus lettuce", sow_period: 2..8, grow_period: 4..8, harvest_period: 5..10 },
  { name: "asparagus pea", description: "", sow_period: 11..12, grow_period: 3..6, harvest_period: 7..9 },
  { name: "basil", description: "Repels Mosquitoes", sow_period: 3..7, grow_period: 4..8, harvest_period: 5..10 },
  { name: "beetroot", description: "", sow_period: 2..8, grow_period: 4..10, harvest_period: 4..10 },
  { name: "bittercress", description: "",  grow_period: 3..8, harvest_period: 5..11 },
  { name: "black pepper", description: "", sow_period: 3..4, grow_period: 6..7, harvest_period: 8..10 },
  { name: "black radish", description: "", sow_period: 3..8, grow_period: 4..8, harvest_period: 5..12 },
  { name: "blue huckleberry", description: "", sow_period: 1..12, grow_period: 1..6, harvest_period: 7..9 },
  { name: "borage", description: "Repels Tomato Worms" },
  { name: "bramble", description: "", sow_period: 11..12, grow_period: 1..5, harvest_period: 7..10 },
  { name: "broad bean", description: "", sow_period: 1..2, grow_period: 3..4, harvest_period: 6..8 },
  { name: "broccoli", description: "", sow_period: 2..4, grow_period: 6..7, harvest_period: 8..9 },
  { name: "brussels sprout", description: "", sow_period: 2..4, grow_period: 5..6, harvest_period: 9..12 },
  { name: "bush beans", description: "Repels " },
  { name: "cabbage", description: "", sow_period: 1..3, grow_period: 4..5, harvest_period: 5..6 },
  { name: "cabbage lettuce", description: "", sow_period: 3..4, grow_period: 5..8, harvest_period: 5..11 },
  { name: "cantaloupe", description: "Repels " },
  { name: "carrot winter carrots", description: "", grow_period: 5..7, harvest_period: 8..12 },
  { name: "carrots", description: "Repels " },
  { name: "cauliflower", description: "", sow_period: 2..3, grow_period: 4..6, harvest_period: 7..8 },
  { name: "celeriac", description: "", sow_period: 2..3, grow_period: 4..5, harvest_period: 9..12 },
  { name: "celery", description: "", sow_period: 2..3, grow_period: 3..4, harvest_period: 7..10 },
  { name: "chard", description: "", sow_period: 3..8, grow_period: 3..11, harvest_period: 5..11 },
  { name: "chicory", description: "",  grow_period: 5..6, harvest_period: 9..10 },
  { name: "chicory roots", description: "", sow_period: 4..5, grow_period: 5..6, harvest_period: 1..12 },
  { name: "chinese cabbage", description: "", sow_period: 3..8, grow_period: 4..8, harvest_period: 5..10 },
  { name: "chives", description: "Repels Aphids and Japanese Beetles" },
  { name: "corn", description: "Repels " },
  { name: "corn salad", description: "", grow_period: 3..9, harvest_period: 4..12 },
  { name: "cos lettuce", description: "", sow_period: 2..7, grow_period: 4..8, harvest_period: 6..9 },
  { name: "cucumber", description: "", sow_period: 3..4, grow_period: 5..6, harvest_period: 7..9 },
  { name: "cutted union 1st yr.", description: "", grow_period: 4..7, harvest_period: 7..8 },
  { name: "cutted union 2nd yr.", description: "", grow_period: 3..4, harvest_period: 7..8 },
  { name: "dill", description: "Repels " },
  { name: "eggplant", description: "", sow_period: 3..4, grow_period: 6..8, harvest_period: 9..10 },
  { name: "endive", description: "", sow_period: 3..7, grow_period: 4..8, harvest_period: 7..11 },
  { name: "field pea", description: "", sow_period: 2..3, grow_period: 3..6, harvest_period: 6..7 },
  { name: "garden cress", description: "", sow_period: 1..12, grow_period: 3..10, harvest_period: 1..12 },
  { name: "garlic", description: "",  grow_period: 1..12, harvest_period: 6..7 },
  { name: "gherkin", description: "", sow_period: 4..5, grow_period: 5..6, harvest_period: 7..9 },
  { name: "green bean", description: "",  grow_period: 5..6, harvest_period: 7..9 },
  { name: "hamburg root parsley", description: "", grow_period: 4..9, harvest_period: 10..11 },
  { name: "haricots verts", description: "", sow_period: 3..4, grow_period: 5..7, harvest_period: 8..9 },
  { name: "iceberg lettuce", description: "", sow_period: 3..7, grow_period: 4..8, harvest_period: 6..11 },
  { name: "indian cress", description: "",  grow_period: 4..6, harvest_period: 7..9 },
  { name: "kale", description: "", sow_period: 5..6, grow_period: 7..12, harvest_period: 1..12 },
  { name: "kohlrabi", description: "", sow_period: 3..7, grow_period: 4..8, harvest_period: 6..11 },
  { name: "leek summer harvest", description: "", sow_period: 1..3, grow_period: 3..7, harvest_period: 7..9 },
  { name: "lettuce", description: "", sow_period: 2..8, grow_period: 4..8, harvest_period: 5..10 },
  { name: "maize", description: "", sow_period: 4..5, grow_period: 5..6, harvest_period: 6..9 },
  { name: "marigolds", description: "Repels Bean Beetles, Aphids, Potato Bugs, Squash Bugs, Nematodes, and Maggots" },
  { name: "marjoram", description: "Repels " },
  { name: "melon", description: "", sow_period: 4..6, grow_period: 6..8, harvest_period: 8..10 },
  { name: "mustard", description: "", sow_period: 3..8, grow_period: 3..10, harvest_period: 4..10 },
  { name: "napa cabbage", description: "", sow_period: 3..7, grow_period: 4..8, harvest_period: 6..10 },
  { name: "nasturtiums", description: "Repels Aphids, Potato Bugs, Squash Bugs, Striped Pumpkin Beetles, and Mexican Bean Beetles. Destroys whiteflies in greenhoues." },
  { name: "neep", description: "", sow_period: 1..12, grow_period: 3..8, harvest_period: 3..9 },
  { name: "new zealand spinach", description: "", sow_period: 3..5, grow_period: 6..7, harvest_period: 6..11 },
  { name: "onions", description: "Repels Many insects/pests–especially maggots" },
  { name: "oregano", description: "Repels Many insects/pests" },
  { name: "parnips", description: "Repels " },
  { name: "parsley", description: "Repels " },
  { name: "parsnip", description: "", sow_period: 3..4, grow_period: 4..9, harvest_period: 10..12 },
  { name: "pea", description: "", sow_period: 2..3, grow_period: 4..5, harvest_period: 6..7 },
  { name: "pearl onion", description: "",  grow_period: 3..5, harvest_period: 7..8 },
  { name: "peppers", description: "Repels ", sow_period: 1..4, grow_period: 3..6, harvest_period: 5..8},
  { name: "pole beans", description: "", sow_period: 5..6, grow_period: 6..7, harvest_period: 7..9 },
  { name: "pole haricot", description: "",  grow_period: 5..7, harvest_period: 8..9 },
  { name: "potato", description: "", sow_period: 3..4, grow_period: 4..6, harvest_period: 7..9 },
  { name: "pumpkin", description: "", sow_period: 4..5, grow_period: 5..8, harvest_period: 8..9 },
  { name: "purslane", description: "", sow_period: 4..8, grow_period: 7..8, harvest_period: 7..9 },
  { name: "radicchio autumn harvest", description: "", sow_period: 2..3, grow_period: 5..6, harvest_period: 9..10 },
  { name: "radish", description: "", sow_period: 1..3, grow_period: 4..9, harvest_period: 4..10 },
  { name: "red cabbage", description: "", sow_period: 1..3, grow_period: 4..5, harvest_period: 5..6 },
  { name: "red raspberry", description: "",harvest_period: 7..10 },
  { name: "rhubarb", description: "", sow_period: 4..5, grow_period: 9..12, harvest_period: 4..8 },
  { name: "romaine lettuce", description: "", sow_period: 2..3, grow_period: 4..9, harvest_period: 4..11 },
  { name: "romanesco", description: "", sow_period: 4..7, grow_period: 4..7, harvest_period: 7..11 },
  { name: "rosemary", description: "Repels Bean Beetles, Cabbage Moths, and Carrot Flies" },
  { name: "runner bean", description: "",  grow_period: 5..6, harvest_period: 8..9 },
  { name: "rutabagas", description: "Repels " },
  { name: "sage", description: "Repels Cabbage Moths and Carrot Flies" },
  { name: "salsify", description: "",  grow_period: 4..5, harvest_period: 1..12 },
  { name: "savoy cabbage", description: "", sow_period: 1..4, grow_period: 4..5, harvest_period: 5..6 },
  { name: "scallion", description: "", sow_period: 2..6, grow_period: 4..7, harvest_period: 6..9 },
  { name: "shallot", description: "",  grow_period: 3..4, harvest_period: 7..8 },
  { name: "snap beans", description: "",  grow_period: 3..4, harvest_period: 5..9 },
  { name: "snow pea", description: "", sow_period: 3..4, grow_period: 4..5, harvest_period: 6..7 },
  { name: "sowing onion", description: "", sow_period: 1..3, grow_period: 4..8, harvest_period: 8..9 },
  { name: "soybeans", description: "Repels " },
  { name: "spinach", description: "", sow_period: 1..2, grow_period: 1..8, harvest_period: 4..11 },
  { name: "strawberry", description: "",  grow_period: 8..9, harvest_period: 6..10 },
  { name: "string bean", description: "",  grow_period: 3..4, harvest_period: 7..9 },
  { name: "summer carrots", description: "", sow_period: 3..4, grow_period: 4..6, harvest_period: 6..9 },
  { name: "summer harvest", description: "", sow_period: 3..5, grow_period: 5..7, harvest_period: 7..8 },
  { name: "sunflowers", description: "Repels " },
  { name: "sweet corn", description: "", sow_period: 4..5, grow_period: 6..8, harvest_period: 8..10 },
  { name: "swiss chard", description: "Repels " },
  { name: "tarragon", description: "Repels " },
  { name: "thyme", description: "Repels Cabbage Moths" },
  { name: "tomatoes", description: "", sow_period: 2..3, grow_period: 5..7, harvest_period: 7..10 },
  { name: "topinambour", description: "",  grow_period: 3..4, harvest_period: 10..11 },
  { name: "tree onions", description: "",  grow_period: 3..6, harvest_period: 6..8 },
  { name: "turnip", description: "",  grow_period: 3..5, harvest_period: 7..10 },
  { name: "turnip tops", description: "", sow_period: 1..2, grow_period: 3..5, harvest_period: 5..11 },
  { name: "watercress", description: "",  grow_period: 3..6, harvest_period: 4..11 },
  { name: "welsh onion", description: "", sow_period: 1..3, grow_period: 4..5, harvest_period: 7..10 },
  { name: "wild strawberry", description: "", sow_period: 11..12, grow_period: 1..4, harvest_period: 5..7 },
  { name: "winter harvest", description: "",  grow_period: 6..8, harvest_period: 1..4 },
  { name: "winter purslane", description: "", sow_period: 7..10, grow_period: 8..10, harvest_period: 1..12 },
  { name: "winterunions", description: "",  grow_period: 8..12, harvest_period: 5..6 },
  { name: "zucchini", description: "", sow_period: 4..6, grow_period: 5..7, harvest_period: 9..11 }
])
